### ISSUE TITLE
Meeting#2

### ISSUE THREAD

**Issue by tokidrill** [nsuzuki7713/a6s-cloud-front#12]
まずは日程調整から。

# 決めること
- [x] 日にち
  3/3 (日)
- [x] 時間
  14:00～
- [x] online or offline
  対面
- [x] 場所
  * 御徒町のLIG(前回と同じ場所)
- [x] 参加者
  * 全員(4人)

# 備考
新規メンバーjoinのため、新規メンバーに合わせたい。

# 議題
- [x] 自己紹介
- [x] 新規メンバーに開発の予定、スケジュール、理念の説明、合意を得る
- [x] 前回の打ち合わせからの進捗、計画の共有
  - [x] Kanban方式のプロジェクト管理の導入について #24
- [x] PHPとPythonの役割設計 nsuzuki7713/a6s-cloud-backend/issues/22
- [x] 新規メンバーに諸々のハンズオン(環境構築がメインになるか。)
  #27
- [x] 仕掛中のissueのフォローや、対面でなければ難しい課題のクリア
- [x] 全体的な概算工数を皆で見積もり

**Comment by tokidrill** [comment]
日程と場所は新規メンバーがslackに参加してからでいいかな。
まずは議題に過不足ないかを検討しましょう。

**Comment by nsuzuki7713** [comment]
議題がMECE過ぎて、僕は言うことないですね。
> 対面でなければ難しい課題

この辺を集まる前に各々事前に出し合う感じですかね。

**Comment by TsutomuNakamura** [comment]
議題MECE で自分も言うことありません！！良いと思います。
// MECE 初めて知った

**Comment by tokidrill** [comment]
それでは、
> * 前回の打ち合わせからの進捗、計画の共有

進捗に関しては、まだそこまで活発に開発していける状態ではないと思うので、皆さんやったことザッと確認しておいてください！
その上で、安心して開発できる土壌作りに不足がないかと、どこから作っていくかを決めていくという形でいきましょう！

> * 仕掛中のissueのフォローや、対面でなければ難しい課題のクリア

日付が決まってから躓いているissueを挙げていって、当日みんなで解決する必要があるものかどうかを吟味することにしましょう。

新メンバーがslackに来てくれるの楽しみだなぁ

**Comment by tokidrill** [comment]
## ミーティングの準備
* 新規メンバー(みのきちさん)用、または再利用のために環境構築を手順化する。
 * Laravel->DB、front->backend の疎通までは確認して共有しておきたい。

**Comment by nsuzuki7713** [comment]
- backendのtweetデータ取得はphpで取得する？

**Comment by tokidrill** [comment]
> * backendのtweetデータ取得はphpで取得する？

backend側にissue切りました。
僕もどこまでissueを使うかは模索中なのですが、議題はissue
にまとめてミーティングのissueにタスクリストとして羅列するという方法を試してみたいので、一度これでやらせてください。

**Comment by nsuzuki7713** [comment]
なおと備忘録
トキさんにPHPの缶バッチとgit hubのシールを持っていく

**Comment by TsutomuNakamura** [comment]
### ■ハンズオン
議題が一通り片付いた後に…

* @tokidrill さん、@minokich さんの環境構築
* ペアプログラミングで[設計書通りのテーブルを作成する #21](https://github.com/nsuzuki7713/a6s-cloud-backend/issues/21)。個人的な希望としてはドライバ: @tokidrill さん、ナビゲータ: その他の方々

### ■自己紹介(勝手に追加)
@minokich さんが新規に入るので改めて全員、簡単な自己紹介

**Comment by nsuzuki7713** [comment]
議事録をkibelaに作成したので、不足点があれば追記お願いします。
振り返りや改善点などありましたら、コメント欄とかに残して頂ければです。
https://a6s-cloud.kibe.la/notes/16
