### ISSUE TITLE
自己紹介ページの作成

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#14]
- [x] kibelaに書く
https://a6s-cloud.kibe.la/notes/11
   - [x] なおと
   - [x] Toki
   - [x] つとむ
   - [x] みのきち

- [x] Readmeにリンクを貼り付ける(なおとタスク)

**Comment by tokidrill** [comment]
更新しました。
メンバー全員更新終了したので、リンクの方お願いします。 @nsuzuki7713

**Comment by nsuzuki7713** [comment]
皆さまー、素敵な自己紹介ありがとうございます😍
