### ISSUE TITLE
「Vue.extend」と「Class Component」の書き方統一

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#19]
Vueの書き方ができる「Vue.extend」が良いのかなと思ってます。
https://qiita.com/potato4d/items/c9c0c8e674f20c85948a#vueextend%E3%81%A8class-component%E4%BA%8C%E3%81%A4%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9

少し触ってvueを触ってもらって書きやすいほうにしましょう😊

**Comment by TsutomuNakamura** [comment]
なんとなくな感覚的な話になってしまいますが、vue-class-component は昔ながら👴のオブジェクト指向+アノテーションのような書き方なイメージです(悪くは無いと思います)。
リンク先の記事もVue.extend メインに語られているのでVue.extend で方針決めしてしまって良いのではないでしょうか👍？

**Comment by nsuzuki7713** [comment]
では、Vueを初めて触る人が多いので「Vue.extend」で進めましょう😊
