### ISSUE TITLE
第三回 打ち合わせ

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#28]
とりあえず、第三回打ち合わせのissueを立てておきます。

# 決めること
- [ ] 日にち

- [ ] 時間

- [ ] online or offline

- [ ] 場所

- [ ] 参加者
  * 全員(4人)

# 備考
- [ ] トキさんにPHPの缶バッチとgit hubのシールを持っていく(なおと)
# 議題

**Comment by tokidrill** [comment]
次回の議題としては、
*  #30 のまとめ
* バックエンドの設計の確認
* issueの分割になるかな？

こちらは意外とあーだこーだ行って戻りの作業とかが多くなるなぁと感じたので、それぞれissueを切って叩いてから総括、という形で作業を進めて行きたいです。

**Comment by nsuzuki7713** [comment]
- #38 について教えてもらう

**Comment by nsuzuki7713** [comment]
- #39 任意参加で実施

**Comment by TsutomuNakamura** [comment]
とりまとめありがとうございます。

3 回目のミーティングですが...
23(土), 24(日)  // 例の呑み会考えるなら23(土)!?
あたりができそうです。

それ以降の空いている日としては4 月入ってからとなりそうです。

**Comment by nsuzuki7713** [comment]
内容が薄いですが、議事録纏めました。
https://a6s-cloud.kibe.la/notes/17
