### ISSUE TITLE
github Projectsの導入

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#29]
#24 で導入が決定
この辺はTokiさんが知見を持っている

**Comment by TsutomuNakamura** [comment]
これ、早速触ってみたいです。導入が楽しみです🤩ウキウキ

**Comment by tokidrill** [comment]
ハイプライオリティで着手させてもらいます。

**Comment by nsuzuki7713** [comment]
とりあえず、作ってみました。
Manage automationは全部にチェックいれたので、issueやプルリクに紐付いているはず。
3つのボードのみですが、追加したほうがいいものとかありますしょうか？
