### ISSUE TITLE
フロントの要件・仕様再検討

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#30]
# 初期リリース時の機能案
全ユーザーに解析可能にしてしまうと解析結果一覧がカオスになる。
初期リリースでは解析できる人は主催者のみにする。プラスして、Commpassのデータをクローリングして自動で解析するようにしてみてはどうでしょうか？
一般ユーザー(勉強会参加者)は結果確認のみとする。
### 主催者
- 主催者は勉強会の反響が気になるはず
- 能動的に解析したいと思うだろう
- 結果をtwitterとかでツイートするだろう

### 一般ユーザー
- 基本は受け身
- 自分から解析したいと思う人は少なそう
- twitterから結果のみを見にくると思う

### 主催者(管理者)
- 解析することができる
  - 日付は「勉強会当日」と「当日+次の日」の2回で集計する

### 一般ユーザー
- 解析結果を確認できる
- 解析結果を検索できる

## その他
- commpassをクローリングして当日実施されていて、ハッシュタグがある勉強会は夜間に自動解析を行う
- 解析完了したら、a6s-cloudで自動ツイート

### 解析結果一覧画面
- 一般ユーザが見る画面
- 主催者や自動で解析した勉強会の結果が一覧表示されている

### 個別結果画面
- word cloudなどの結果を確認できる

### 解析画面
- 主催者が解析依頼する画面
- パスを切り分けることで一般ユーザからはアクセスできないようにする。
- パスは主催者に個別付与？？←ここは要検討

**Comment by nsuzuki7713** [comment]
ひとまずたたき台を上げました。どしどしご意見お願いしまーす。
イメージはラフ画で書いてみようと思います。

**Comment by TsutomuNakamura** [comment]
まとめありがとうございます。色々参考になります🤩。

> 日付は「勉強会当日」と「当日+次の日」の2回で集計する

これは、例えば勉強会が2019/03/03 19:00 〜21:00 に実施されて主催者が2019/03/03 21:30 に解析依頼したら、その解析依頼に加えてバックエンド側で2019/03/04 21:30 に再度解析実行するように…みたいなジョブを登録するような機能実装しておいたほうが良い、という意味合いでしょうか？
もしそうであれば、バックエンド側の機能に含む必要があると思うので、気兼ねなく言ってください👍。

> パスを切り分けることで一般ユーザからはアクセスできないようにする。
> パスは主催者に個別付与？？←ここは要検討

それでOK かと思います。ただ将来的に利用者が増えてきた時に、何か認証のような機能が必要になってくる気がしています。
主催者かどうかを外部のAPI とかで知る方法とかありますでしょうか(もしなければこれから皆で考えて行ければよいかと、楽観的に考えています)！？あればそこから主催者であるかどうかを解析して、そうでなければ拒否する…みたいな処理を実装する必要もあるかと思います。
...ただ、今はまだ考える必要も無いかもしれません。この認証が必要化どうかの件は後回しでも良い気がしています。

**Comment by nsuzuki7713** [comment]
ざっくり画面イメージを考えましたー

# 解析依頼画面
![ios 5](https://user-images.githubusercontent.com/34429882/53695413-d2416780-3dfe-11e9-87cd-85519bed0827.jpg)

# 解析結果画面
![ios 6](https://user-images.githubusercontent.com/34429882/53695428-02890600-3dff-11e9-8dcc-deeed6b579d5.jpg)

# 解析個別画面
![ios 7](https://user-images.githubusercontent.com/34429882/53695419-ed13dc00-3dfe-11e9-883e-92618e85adfa.jpg)

**Comment by TsutomuNakamura** [comment]
良いと思います💪。
あとはこれをVue やElement UI、D3.js とかで、どのくらい表現できるかだと思います。

**Comment by nsuzuki7713** [comment]
>これは、例えば勉強会が2019/03/03 19:00 〜21:00 に実施されて主催者が2019/03/03 21:30 に解析依頼したら、その解析依頼に加えてバックエンド側で2019/03/04 21:30 に再度解析実行するように

→チェックボックスを付けて最大3回解析できるようにしてみました。時間も入れたほうがいいのかな🤔
どちらにせよ、バックエンドに機能追加は必要そうです。。

>主催者かどうかを外部のAPI とかで知る方法とかありますでしょうか

→commpassの管理者から確認？？でもとりあえず、最初は性善説で考えてます笑

**Comment by tokidrill** [comment]
> 主催者かどうかを外部のAPI とかで知る方法とかありますでしょうか

主催者のログイン機能を持たせて、主催者のプロパティにハッシュタグを登録できるようにする。
登録したハッシュタグのみ解析依頼をリクエストできる、とかすれば ハッシュタグ(イベント)と会員(主催者)のひも付きがわかるんじゃないでしょうか？？

うーん、この認証は要件詰めが少し面倒なので、初期はパスを切り分けて… のみで十分な気もしますね。
参加者側にそのパスを教えないのであれば、イタズラ防止策とかはBasic認証とかでもいい気がするし、それも必要かどうかというとそうでもない気がします。
ただ、デリケートなフォームをネットの海に裸で置いておくのはちょっと怖い気もしますね。

**Comment by tokidrill** [comment]
解析画面のラフもいい感じのような気がします！
解析タイミングを3つから複数選択できるのもgoodな気がします！

一般ユーザが遊ぶために口コミ投稿できるようにしては？… と思いましたが、ハッシュタグ付きのツイート自体が勉強会の口コミになっているので、必要ないですね。
「今スグtwitterでハッシュタグ付きのツイートを見る」的なリンクからtwitter上で該当のハッシュタグ付きのツイート一覧を見れるようにしたら、便利かもですね。

**Comment by TsutomuNakamura** [comment]
> →チェックボックスを付けて最大3回解析できるようにしてみました。時間も入れたほうがいいのかなthinking
> どちらにせよ、バックエンドに機能追加は必要そうです。。

> →commpassの管理者から確認？？でもとりあえず、最初は性善説で考えてます笑

了解です。良いと思います。一旦それで固めてGo してみましょうか！！

**Comment by nsuzuki7713** [comment]
>「今スグtwitterでハッシュタグ付きのツイートを見る」

→これは面白いですね。是非付けたいです。

一旦、この画面で進める感じでもよろしいでしょうか？
バックエンドの設計は考え直す必要がありそうですが、フロントの画面作成は進められそうです。

**Comment by TsutomuNakamura** [comment]
はい、要件固まってきましたしこれで進めて良いと思います🙆‍♂️
