### ISSUE TITLE
python(word cloud)バッチのリポジトリを分けるか？

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#31]
### slackメモ
ほぼそのままで外部コマンドとして呼び出せるのであれば、submodule として取りべきと思いますし、カスタマイズが必要なのであれば別リポジトリ新たにリポジトリ作成する方向になるのかなと考えています。

そこですみません…python のライブラリとして何を使うか聞いていなかったのが悪いのですが、Word Cloud の画像生成にはなおとさんのpython のスクリプトを使う感じでしょうか？
https://github.com/nsuzuki7713/twitter-analysis

それともamueller 氏のpython ライブラリを使う感じでしょうか？
https://github.com/amueller/word_cloud

そのあたりでウチらの要件に合うものを選んだり、仕様を調べたりしてsubmodule として取り入れるべきか新しくリポジトリ作成(カスタマイズ)するかも変わってくるのかなと思いました。

**Comment by nsuzuki7713** [comment]
僕が作成したスクリプトもWord Cloudライブラリはamueller氏のを使っています。
事前前処理(データ取得や形態素)は自前で実装する感じです。

今回python側でする処理は、

1. テキストファイルの読み込み
2. 形態素解析の実施
3. word cloud処理

になると思います。形態素解析などはチューニングする可能性はあります！！

そして、submoduleの概念があまり分かっていないです🤔
他の人が作ったライブラリを叩くだけなら、submoduleとして同一リポジトリにいれる？
自分たちでカスタマイズする場合はリポジトリを作成したほうがよい？

**Comment by TsutomuNakamura** [comment]
情報ありがとうございます！
> テキストファイルの読み込み
> 形態素解析の実施
> word cloud処理

なるほど、本家のプログラムにそのあたりに追加が必要なのですね。
そのあたりが必要なことを踏まえると、
なおとさんのが使いまわせたらうれしい気がします。
あとは前回ミーティング時に出た要件である…
(1)ツイート情報を保存した、解析対象ファイルの
　PathをPython ライブラリ側に指定できる
(2)Python ライブラリが呼び出し元のプログラム(PHP)に
　画像ファイル出力先のPATH を標準出力などで教えることができる
　(もしくは呼び出し元のPHP で、Python のライブラリに対して
　出力先を指定することができるでもよいと思います)
このあたりについてはカスタマイズが必要だったりしますでしょうか！？

**Comment by TsutomuNakamura** [comment]
> そして、submoduleの概念があまり分かっていないですthinking
> 他の人が作ったライブラリを叩くだけなら、submoduleとして同一リポジトリにいれる？
> 自分たちでカスタマイズする場合はリポジトリを作成したほうがよい？

すみません、自分の伝え方も下手なのですが…
例えば今、a6s-cloud-backend リポジトリに
laradock をsubmodule として取り入れていますが、
submodule はあくまでlaradock リポジトリ(https://github.com/laradock/laradock)への
参照を持っているだけになります。
そこで「laradock をa6s-cloud 用にカスタマイズしたいな」と思って
clone 済みのlaradock/ 下の資材を編集してコミットしても
https://github.com/laradock/laradock にpush する権限がないため
カスタマイズができないという状態になってしまいます。。
なのでもしカスタマイズしたいという要望が出てきた場合は、
laradock をfork するなどしてチーム内にリポジトリを作成し、
そちらをsubmodule してコミットもpush もできるようにしたほうが良いかなと思いました。
// 今回のPython のやつの件については、なおとさんのを使うことに決まれば
// submodule しても我々側でそれをコミット、
// push できると思うのでカスタマイズも問題なくできると思います

…ちょっと伝えかたがまだ足りていなかったら、コメントいただければと思います。

**Comment by nsuzuki7713** [comment]
submoduleって参照なんですね。初めて知りました。
a6s-cloud-backendの下にlaradockあるので、個別編集できると思っていました。
そう考えると、a6s-cloudのpython用のリポジトリを作成して、a6s-cloud-backendにsubmoduleとして組み込む感じですかね。

python側で更新があった際は、a6s-cloud-backendのsubmoduleはどうやって更新するのでしょうか？

**Comment by TsutomuNakamura** [comment]
> a6s-cloudのpython用のリポジトリを作成して、a6s-cloud-backendにsubmoduleとして組み込む感じですかね。

はい、そのような感じで良いかと思います。
python 側で変更があった場合は、
> git submodule update --init --recursive

コマンドで再度python 側のモジュールを取得してくるような感じでできるかと思います😁

**Comment by nsuzuki7713** [comment]
batch用のリポジトリを新規作成
https://github.com/nsuzuki7713/a6s-cloud-batch
