### ISSUE TITLE
解析結果一覧画面のプロトタイプ作成

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#36]
#30 が要件です。
APIの設計が出来ていないため、マークアップからお願いします。
画面はイメージなので、自由にいい感じにしてください🥳

#41 がAPIの設計です

![53695428-02890600-3dff-11e9-8dcc-deeed6b579d5](https://user-images.githubusercontent.com/34429882/53882978-26488800-405b-11e9-8ca4-6d221d1ad303.jpg)

**Comment by TsutomuNakamura** [comment]
解析結果一覧画面に立候補します💁‍♂️。
ステータスがバックエンド側とどの程度まで同期できるのか色々検証してみたいためです。
バックエンド側と並行で作業して遅れそうであれば、譲りますのでコメントください。

**Comment by nsuzuki7713** [comment]
こちらのissueは一旦クローズしても良さそうです！！
余裕があればリファクタや共通化処理のissueの作成お願いしたいです🙇‍♂️
issue作成したら、僕もコードを見ながらお願いしたいことを追記しますね。

**Comment by TsutomuNakamura** [comment]
了解です！では一旦クローズします。
