### ISSUE TITLE
解析結果のプロトタイプ作成

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#37]
#30 が要件です。
APIの設計が出来ていないため、マークアップからお願いします。
画面はイメージなので、自由にいい感じにしてください🥳

#40 がAPIの設計です。

![53695419-ed13dc00-3dfe-11e9-883e-92618e85adfa](https://user-images.githubusercontent.com/34429882/53883030-46784700-405b-11e9-8f00-990288df411f.jpg)

**Comment by minokich** [comment]
解析結果画面の担当に立候補します。
画像の取り扱い周りを個人開発のアプリ(放置気味ですが・・・)で行おうとしていたので、
ちょうど勉強したいなと考えていました。

**Comment by nsuzuki7713** [comment]
関連issueを対応したので、クローズします！！
