### ISSUE TITLE
解析結果一覧のAPI設計

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#41]
# 3/10追記
レスポンスは設計案から変わっています。実装側のレスポンスを正としてください。
nsuzuki7713/a6s-cloud-backend/pull/37

# エンドポイント
条件で指定した検索結果一覧を返すAPI
Get `/api/v1/AnalysisResultLists`

# Parameters
| prams | required | Description |
----|---- |---- 
| serach_word | × | 検索ワード |
| page | × | 取得ページ(取得件数は要確認) |

# Responses
| values| Description |
---- |---- 
| id | 連番(key) |
| analysis_start_date | 分析開始日付 |
| analysis_end_date | 分析終了日付 |
| analysis_word | 分析ワード |
| status| ステータス |
| favorite_count | いいね数 |
| user_count | ユーザー数 |
| tweet_count | ツイート数 |
| url | url |
| insert_date | 追加日時 |
| update_date | 更新日時 |

オブジェクトの配列を返すイメージです。
```
[
  {
    "id": 1,
    "analysis_start_date":"2019/03/01 12:00:00",
    "analysis_end_date":"2019/03/02 12:00:00",
    "analysis_word":"a6s-cloud",
    "status":"完了",
    "favorite_count":12,
    "user_count":33,
    "tweet_count":123,
    "url": "https://github.com/nsuzuki7713/a6s-cloud-front/"
    "insert_date":"2019/03/01 12:00:00",
    "update_date":"2019/03/01 12:00:00",
  },
  {
    "id": 2,
    "analysis_start_date":"2019/03/01 12:00:00",
    "analysis_end_date":"2019/03/02 12:00:00",
    "analysis_word":"a6s-cloud",
    "status":"完了",
    "favorite_count":12,
    "user_count":33,
    "tweet_count":123,
    "url": "https://github.com/nsuzuki7713/a6s-cloud-front/"
    "insert_date":"2019/03/01 12:00:00",
    "update_date":"2019/03/01 12:00:00",
  },
]
```

**Comment by TsutomuNakamura** [comment]
API 設計ありがとうございます。
何か変な文章あればご連絡いただければと思います。

* Parameters にsearch_word が指定されなかった場合
  API Server は全検索ワードを対象にレスポンスを作成するでよいでしょうか(新しいのから順にとってくるイメージ)？
* Parameters にpage が指定されなかった場合
  API Server はデフォルトで1 ページ目を返すで良いでしょうか？
* statu -> status (typo がありました)
* favorite_count やuser_count はint 型が良いと思いました(id はint 型になっていました)
* 解析依頼を出すエンドポイント、API 設計もいただきたいです🙇‍♂️

**Comment by nsuzuki7713** [comment]
> - Parameters にsearch_word が指定されなかった場合
API Server は全検索ワードを対象にレスポンスを作成するでよいでしょうか(新しいのから順にとってくるイメージ)？

→全検索で、新しい順で良さそうです。search_wordでの検索は全一致ではなく、部分一致ぐらいにしますか。

> - Parameters にpage が指定されなかった場合
API Server はデフォルトで1 ページ目を返すで良いでしょうか？

→デフォルトで1 ページで大丈夫です🙆‍♂️

> - statu -> status (typo がありました)

→修正します！！

> - favorite_count やuser_count はint 型が良いと思いました(id はint 型になっていました)

→ こちらはintですね！！

> 解析依頼を出すエンドポイント、API 設計もいただきたいです

→ 💪

**Comment by TsutomuNakamura** [comment]
ありがとうございます。宜しくおねがいします💪

**Comment by nsuzuki7713** [comment]
urlをレスポンス値に追加
