### ISSUE TITLE
解析依頼画面のAPI設計

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#42]
# エンドポイント
条件で指定した検索結果一覧を返すAPI
Post `/api/v1/AnalysisRequests`

# Parameters
| prams | required | Description |
----|---- |---- 
| start_date | ○ | 開始日付 |
| analysis_word | ○ | 解析ワード |
| url | × | URL |
| analysis_ timing | ○ | 解析タイミング(1: 今すぐ,2: 開始日付日, 3: 次の日) |

```
{
  "start_date": "2018/04/02",
  "analysis_word": "a6s-cloud",
  "url": "https://github.com/nsuzuki7713/a6s-cloud-front/",
  "analysis_ timing": [1,3],
}
```

# Responses
正常に登録出来た場合はstatus code `200` を返して、解析一覧画面へ遷移する

**Comment by TsutomuNakamura** [comment]
仕事が早いです😭
確認しました。自分からは特にコメントありません。大丈夫だと思います🙆‍♂️。

将来の要望になってしまいますがこのままだと誰が作成依頼を出したのかがわからず、また作成依頼を大量に作成させるという攻撃ができてしまうので事前にユーザ認証をさせ、認証トークンもJSON に含めて作成依頼を出すみたいな感じにしたほうが良いと思いました。
認証通っていないものは解析依頼を許可しない、同一ユーザ(token で判別できる)から短時間で何回も来ている場合はモウチョットマッテネ的な意味を込めてエラーを返すといったことも実現できると思いました。

ただ、ひとまずモノができるまでは上記設計で進めても問題ないかなという個人的な感想です😃。

**Comment by nsuzuki7713** [comment]
ありがとうございます！！
ログイン機能実装したらトークンでユーザー管理はしたいですね！！
JSONではなく、ヘッダにトークンを含める感じが良さそうです。
そうすればGetでも認証ができるため。

**Comment by TsutomuNakamura** [comment]
了解です。そうですねヘッダの方が良いかもしれません。それではこれでいきましょう！

**Comment by tokidrill** [comment]
画面と照らして確認しました！

> 条件で指定した検索結果一覧を返すAPI
> Post /api/v1/AnalysisRequests

これって入力に合わせてTwitter APIとWordCloudを叩くAPIですよね？？
細かいですが、僕の認識がずれてたら怖いので、一応確認させてください。

**Comment by nsuzuki7713** [comment]
>これって入力に合わせてTwitter APIとWordCloudを叩くAPIですよね？？
細かいですが、僕の認識がずれてたら怖いので、一応確認させてください。

→そうです！！ただ、バックエンドの設計は再考する必要がありそうです。
