### ISSUE TITLE
READMEをかっこよく

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#46]
参考プロジェクト
- https://github.com/peach-hack/auto-matching
- https://github.com/WEBsinjyuku/meister-hackers

バッチはここで作れる
https://shields.io/

**Comment by tsu-nera** [comment]
私のリポジトリで笑ったw

これもめちゃおすすめです。
* https://allcontributors.org/

**Comment by nsuzuki7713** [comment]
Contributorsを追加してちょっとかっこよくなりました🤤
