### ISSUE TITLE
第四回 打ち合わせ

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#47]
# 決めること
- [x] 日にち
4/28(日) 
- [x] 時間
10:00〜18:00

- [x] online or offline
online

- [x] 場所
池袋のいいオフィス

- [x] 参加者
  * 全員(4人)

# 備考
- [x] トキさんにPHPの缶バッチとgit hubのシールを持っていく(なおと)
**→これ必須！！！**

- [x] 調整さん
https://chouseisan.com/s?h=789877ae0dcc4f95b6be9279d7274e6e

# 議題
- 進捗報告
- https://github.com/nsuzuki7713/a6s-cloud-backend/issues/105
- https://github.com/nsuzuki7713/a6s-cloud-backend/issues/110
- https://github.com/nsuzuki7713/a6s-cloud-front/issues/70
- https://github.com/nsuzuki7713/a6s-cloud-front/issues/49
- タスク整理
- モブプロ等で新規実装もしくはリファクタリング
- WDD（都合が合えば）

**Comment by TsutomuNakamura** [comment]
池袋のいいオフィスの無料券(割引券)わすれずに！

**Comment by TsutomuNakamura** [comment]
第4回の活動内容ですが、1 つとしてToki さん担当のフロント画面のモブプログラミングとかどうでしょう🙋‍♂️！？

**Comment by nsuzuki7713** [comment]
いいですね！！何かしらのモブプロしてみましょう！！

**Comment by nsuzuki7713** [comment]
# 追加したissue
#71 
#72 
https://github.com/nsuzuki7713/a6s-cloud-backend/issues/113
https://github.com/nsuzuki7713/a6s-cloud-backend/issues/114
https://github.com/nsuzuki7713/a6s-cloud-backend/issues/115
https://github.com/nsuzuki7713/a6s-cloud-front/issues/73

**Comment by nsuzuki7713** [comment]
議事録
https://a6s-cloud.kibe.la/notes/35
