### ISSUE TITLE
a6s-cloud のメインカラーを決める

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-front#49]
a6s-cloud のメインカラーを決め、テーブルやラベルの色として何の色を使うか統一したい。

Element UI が使う色に合わせて選択するのが良い(?)

https://element.eleme.io/#/en-US/component/color

**Comment by TsutomuNakamura** [comment]
作成途中のサンプル

青系:
![p1](https://user-images.githubusercontent.com/10674169/55283299-06c32780-539b-11e9-9564-eec8d2345b35.jpg)

緑系:
![p2](https://user-images.githubusercontent.com/10674169/55283305-222e3280-539b-11e9-80fa-0ec7387fa25c.jpg)

オレンジ系:
![p3](https://user-images.githubusercontent.com/10674169/55283307-340fd580-539b-11e9-9a76-52613a36d084.jpg)

赤系:
![p4](https://user-images.githubusercontent.com/10674169/55283318-7df8bb80-539b-11e9-8e1f-831b775dde94.jpg)

グレー系:
![p5](https://user-images.githubusercontent.com/10674169/55283320-8d780480-539b-11e9-9fcb-31c63559c70b.jpg)

**Comment by nsuzuki7713** [comment]
個人的には青か緑ですかねー

**Comment by TsutomuNakamura** [comment]
自分も青 or 緑かなと考えています。

**Comment by nsuzuki7713** [comment]
一先ず青で。。デザインはのなとさんにお願いしたい。。
