### ISSUE TITLE
システム概要図作成

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#6]
ホワイトボードでメモした内容をいい感じにする
センスがある人はだれだろう。。

**Comment by TsutomuNakamura** [comment]
draw.io で作成してみました(画像は自分のfork したリポジトリにあるやつです)。まだ暫定的で作成途中の状態です。
draw.io なら、ブラウザ版で直接GitHub のを編集できそうです。
もしくはクライアントを自分のマシンにインストールしてclone したリポジトリのファイルを編集してコミットプッシュする形でも編集できると思います。

このあたりから皆が追記していく形で育てていくのはどうでしょうか！？

![p](https://user-images.githubusercontent.com/10674169/53172524-e334f080-3628-11e9-986c-8b86f819d6ad.png)

**Comment by TsutomuNakamura** [comment]
…と作成してから気付いたのですが"UI" ってことは、Web 画面の方だったりしますか🤔!?

**Comment by nsuzuki7713** [comment]
めちゃ、カッコいいです！！図にすると雰囲気でますね！！
テンション上がりますね(´∀｀∩)↑age↑

まだ作りかけだと思いますが、
フロント
　- Vue
　- Typescript
　- element ui
バックエンド
　- PHP
　- Laravel
　- Python
　- MySQL
を入れておきたいです😊

**Comment by TsutomuNakamura** [comment]
了解です。追加してまたプルリク作成しておきます！
