### ISSUE TITLE
【解析結果画面】mouted時にword cloudの画像を取得する

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#65]
backendの対応後に着手
(画像がリクエストで取得できるようにする)

**Comment by TsutomuNakamura** [comment]
なん…だと…😧。既に画像ファイル名取得できるようになっているとは…。仕事早すぎです。
![p](https://user-images.githubusercontent.com/10674169/56844440-188ce180-68eb-11e9-951e-e80cafd2ca76.png)
