### ISSUE TITLE
ナビゲーションを作成する

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-front#68]
解析依頼画面、解析結果一覧画面等へ遷移するためのナビゲーションを作成したい。Element UI にもナビゲーションがありそう。
https://element.eleme.io/#/en-US/component/menu

**Comment by nsuzuki7713** [comment]
激しく同意！！

**Comment by nsuzuki7713** [comment]
のなとさんのデザイン案でお任せするタスクのため、Closeします。
