### ISSUE TITLE
解析依頼画面 「検索ワード」フォームに # のラベルをつける

### ISSUE THREAD

**Issue by tokidrill** [nsuzuki7713/a6s-cloud-front#72]
フォームの前に ```#``` のラベルをつけて、ユーザ入力のフォーマットをわかりやすくする。
リクエスト時には ```#``` 付きの文字列がリクエストされるよう加工する。

**Comment by nsuzuki7713** [comment]
こちらものなとさんのデザイン案でお任せするタスクのため、Closeします。
