### ISSUE TITLE
【解析結果一覧画面】GET パラメータのkey をキャメルケースにする

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-front#85]
解析結果一覧画面でPOST しているKEY を、a6s-cloud のAPI 仕様にあわせてキャメルケースにする(例えばsearch_word)。
(結局Twitter のAPI がスネークケースで統一できないので、対応の必要無しでも良い？)

**Comment by nsuzuki7713** [comment]
なるほど。フロント側から送るキーも考えないといけないのですね。。
現状は下記で統一できていないですよね。
- backend → front（キャメールケース）
- front → backend（スネークケース）

リクエストパラメータもキャメルにして、バックエンド側でスネークに変換対応するか。もしくは今のままで行くか悩ましいところですね。

個人時にはAPIはキャメルケースにして統一させてもいいのかなと思ってます。どう思いますか？？

**Comment by TsutomuNakamura** [comment]
コメありがとうございます。
リクエストパラメータもキャメルにして、バックエンド側でスネークに変換対応する、で認識あっていまか！？自分もそれが良いのかなと思っています。
twitter API から取得できる結果はスネークケースですがTwitterClientService でラップして外から見えないようにしているので、そこだけ例外でスネークケースで処理…で問題ないかと考えています。

**Comment by nsuzuki7713** [comment]
>リクエストパラメータもキャメルにして、バックエンド側でスネークに変換対応する

→僕もこの認識です。ユーザから見れるデータはキャメルにしましょう😊

**Comment by TsutomuNakamura** [comment]
ラジャーです😎

**Comment by TsutomuNakamura** [comment]
先日に引き続き、こちらのほうキャメルケースにしようと思います👻
