### ISSUE TITLE
プルリクのマージ手順

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-front#9]
## つとむさん
個人的には、一人で完了にする、マージはプルリクエストした人以外でする(or マージ得意な担当の人がマージする)が個人的な意見です。せっかくGitHub 使ったアジャイル的でスピード感ある開発なので、堅苦しいプロセスよりはゆるいプロセスのほうが良いかなと感じています。
もし、ミスが会った場合はその切り返しが早いのもこういった開発の利点なのかな…とも思いますので。

## なおと
僕も一人のレビューが通れば基本完了でいいと思います。マージはレビューした人が対応する。

**Comment by tokidrill** [comment]
# Toki の意見
> せっかくGitHub 使ったアジャイル的でスピード感ある開発なので、堅苦しいプロセスよりはゆるいプロセスのほうが良いかなと感じています。
これ賛成です。

併せてですが、レビュワーを誰がやるかとかの依頼の規則も作っておいたほうが、PR出したけど放置になっているとかも減っていいような気がします。
どう思いますか？？

**Comment by nsuzuki7713** [comment]
レビュワーに関してはまだ3人なので、依頼とかの規則はまだいらないかなと思ってます。
今は時間ある人やできる人がslackやプルリクコメントで挙手してやっていく形にして、それでうまく周らない場合は運用ルールを考えるでも良さそうな気もしていましたー

**Comment by TsutomuNakamura** [comment]
> 今は時間ある人やできる人がslackやプルリクコメントで挙手してやっていく形にして
確かに良いと思います。それと同時(?)に自分でやることが決定したときに
Reviewer に(issue の場合はAssigneesに)自分自身を指名する、という使い方もありかなと個人的に考えています。

> PR出したけど放置
続けていくと確かに出てき始めると思いますので、その場合は自分から指名せざるを得ない時が来るかもしれませんね…。

**Comment by nsuzuki7713** [comment]
>自分でやることが決定したときにReviewer に(issue の場合はAssigneesに)自分自身を指名する

→僕も最初はこれでいいのかなと思いました。

>PR出したけど放置

git hubのapi( https://developer.github.com/v3/pulls/ )があるので、放置されたPRがあるときは「ボッコちゃん」が怒りの？通知をしてくれるスクリプトを作っても面白そうですね笑

**Comment by TsutomuNakamura** [comment]
Reviewer もしくはAssignees を指定するということは、誰かに責任をもたせるという意味だけでなく、誰が今このレビューやissue を担当しているかを明確にすることで他の人と作業が重複してしまわないようにという意味も含めていると個人的に思っています。
なのでまずは、自発的に自分ができそうなプルリクのレビューor issue を選択して自分自信をReviewer もしくはAssignees に登録してしまうというのは個人的に提案したいです。
もちろん今ここにいるメンバーは心の広いお方ばかりなので、個々の得意分野等を考慮して他の人を指名したいとき「○○さんにこれお願いできます？」みたいな簡単なコメントした上でReviewer もしくはAssignees に指定するのはありかなと思います。

...というスタンスとかどうでしょうか？
こういう開発はあまり経験がないので、私の勘違いや反論あれば大歓迎ですのでコメントください😭(Yes)。

> git hubのapi( https://developer.github.com/v3/pulls/ )があるので、放置されたPRがあるときは「ボッコちゃん」が怒りの？通知をしてくれるスクリプトを作っても面白そうですね笑

いいですね！時間あるときにお願いしたいです。「いつ終わらせるんだよつとむ😈!!」とか言われたら…あっはいやります、すみません😰、って感じで動き始めると思います(笑)。

**Comment by nsuzuki7713** [comment]
僕はつとむさんの内容で問題なしです！

![download](https://user-images.githubusercontent.com/34429882/52791175-b2ded680-30ab-11e9-8b3b-50b8d0fc6040.jpg)

**Comment by tokidrill** [comment]
いいですね！
怒りのボッコちゃんも賛成です！

では下記の通り
* やりたいissueがあれば自分自身をassigneeとしてassignする
* レビューしたいPRがあった場合は自分自身をReviewerとしてassignする
* ある程度残ってしまっているissueやPRはミーティングやslackで整理する
* ReviewerがLGTMと判断したPRはReviewer自信でMergeする
* "ある程度残っている" 判断はゆくゆくはボッコちゃんに任せたい(笑)

僕の理解に違いがあったり、異論がある方は続くコメントで指摘お願いします！
問題ないという方は♡のリアクションお願いします！
3番めの♡をつけた方はissueのクローズも併せてお願いします！！

**Comment by TsutomuNakamura** [comment]
賛成です。

> 3番めの♡をつけた方はissueのクローズも併せてお願いします！！

承知。。。
クローズします。
